#!/bin/bash
./mvnw package && sudo java -jar --module-path /usr/share/openjfx/lib --add-modules=javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,javafx.web -Dpi4j.debug -Dpi4j.linking=dynamic shade/poketime.jar
